
export const updateUserQueries = [
  'UPDATE User SET firstname = ? WHERE id = ?',
  'UPDATE User SET lastname = ? WHERE id = ?',
  'UPDATE User SET username = ? WHERE id = ?',
  'UPDATE User SET email = ? WHERE id = ?',
  'UPDATE User SET emailCode = ? WHERE id = ?',
  'UPDATE User SET emailCertified = ? WHERE id = ?',
  'UPDATE User SET hashedPassword = ? WHERE id = ?',
  'UPDATE User SET passwordCode = ? WHERE id = ?',
  'UPDATE User SET birthdate = ? WHERE id = ?',
  'UPDATE User SET gender = ? WHERE id = ?',
  'UPDATE User SET region = ? WHERE id = ?',
  'UPDATE User SET tall = ? WHERE id = ?',
  'UPDATE User SET physique = ? WHERE id = ?',
  'UPDATE User SET diet = ? WHERE id = ?',
  'UPDATE User SET popularity = ? WHERE id = ?',
  'UPDATE User SET photo1 = ? WHERE id = ?',
  'UPDATE User SET photo2 = ? WHERE id = ?',
  'UPDATE User SET photo3 = ? WHERE id = ?',
  'UPDATE User SET photo4 = ? WHERE id = ?',
  'UPDATE User SET photo5 = ? WHERE id = ?',
  'UPDATE User SET title = ? WHERE id = ?',
  'UPDATE User SET bio = ? WHERE id = ?',
  'UPDATE User SET pourcentFilled = ? WHERE id = ?',
  'UPDATE User SET lastConnection = ? WHERE id = ?',
  'UPDATE User SET updatedAt = ? WHERE id = ?',
  'UPDATE User SET deletedAt = ? WHERE id = ?',
];

export const updateUserType = [
  'firstname',
  'lastname',
  'username',
  'Email',
  'EmailCode ',
  'emailCertified',
  'HashedPassword',
  'PasswordCode',
  'birthdate',
  'gender',
  'orientation',
  'region',
  'tall',
  'physique',
  'diet',
  'popularity',
  'photo1',
  'photo2',
  'photo3',
  'photo4',
  'photo5',
  'title',
  'bio',
  'pourcentFilled',
  'lastConnection',
  'createdAt',
  'updatedAt',
  'deletedAt',
];


