
networks:
  matcha:
    driver: bridge

services:
 client:
    image: node:lts-alpine
    container_name: client
    working_dir: /client
    restart: always
    env_file:
      - ./client/.env
    ports:
      - 8000:8000
    networks:
      - matcha
    volumes:
      - ./client:/client
    depends_on:
      - server
    command: sh -c "npm install && npm run dev --host"
 server:
    image: node:lts-alpine
    container_name: server
    working_dir: /server
    restart: always
    env_file:
      - ./server/.env
    ports:
      - 8001:8001
    networks:
      - matcha
    volumes:
      - ./server:/server
    depends_on:
      - mysql
    command: sh -c "npm install && npm run dev"
 mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    env_file:
      - ./database/.env
    ports:
      - "3306:3306"
    networks:
      - matcha
