
networks:
  matcha:
    driver: bridge

services:
 client:
    container_name: client
    image: client
    build:
      context: ./client
    restart: always
    env_file:
      - ./client/.env
    ports:
      - 8000:8000
    networks:
      - matcha
    # depends_on:
    #   - server
